### ISSUE TITLE
Tango documentation structure, revising

### ISSUE THREAD

**Issue by HelgaMond** [tango-controls/tango-doc#1]
In order to increase an output of [Tango Write-the-doc camp](http://www.tango-controls.org/community/events/write-docs-camp/), have created a mind map of Table of Contents as I see it.
![tango_docs_mindmap](https://cloud.githubusercontent.com/assets/27626862/25071856/9cc3aa6c-22d2-11e7-83c8-922e58c41eea.png)

If you want, you can change it. I use VYM for this.
[Tango_docs_MindMap.vym.zip](https://github.com/tango-controls/tango-doc/files/924334/Tango_docs_MindMap.vym.zip)

**Comment by andygotz** [comment]
Very good and complete analysis of current and required documentation - thanks! I propose to go through this on the first day at the Write-the-doc camp next week.

**Comment by piogor** [comment]
I think the task is to be closed as the new structure has been proposed and implemented.
