### ISSUE TITLE
Change font size of text

### ISSUE THREAD

**Issue by andygotz** [tango-controls/tango-doc#10]
The font size displayed in the body is quite small on my laptop screen. How can it be increased? I tried to change it by adding this line (copied from django docs) to the source/_theme/tango-cs/static/common.css file:

body {
    color: #222;
    padding: 0;
    /*font-family: avantgarde, sans-serif;*/
    font:12px/1body {.5 Verdana,sans-serif;
}

But it had no effect. Why? How to change the body font size and family?

**Comment by piogor** [comment]
Hi Andy,

Sphinx is not detecting changes in them thus not updating the output. You may need to remove build folder and run sphinx-build again. I have checked the CSS if it is not overwritten in some substyles and it is not.

 

CU tomorrow,

Piotr

**Comment by birkenfeld** [comment]
Note: instead of clearing the whole build folder it is usually enough to just `touch` one source file, which will generate the style output as well.

**Comment by piogor** [comment]
With the new theme it seems to be solved.
