### ISSUE TITLE
Documentation of Tango Installation on CentOS

### ISSUE THREAD

**Issue by hardion** [tango-controls/tango-doc#103]
How to install a bare metal CentOS 7 machine with the basic Tango packages including Archiving, Snapshot, ...
This include also to set up a TangoBox based on CentOS

**Comment by piogor** [comment]
it relates to #310

**Comment by piogor** [comment]
@hardion, the basic installation instruction is here, now: https://tango-controls.readthedocs.io/en/latest/installation/tango-on-linux.html#centos

However, you also mention archiving and snap. I suggest adding these topics under "Administration/Services", where there will be a general part and specific parts for Ubuntu/CentoOS/(Windows?). So, I will create specific issues and close this one. What do you think?

**Comment by piogor** [comment]
@hardion, then, what do mean by this "include also setup of TangoBox on CentOS"?
As the TangoBox is built with scripts, containers + some manual steps (however, all adjusted to Ubuntu), providing a detail instruction for CentOS is feasible but will require quite an effort for testing. Then, currently vast of features on TangoBox are provided as Docker containers based on Debian. Should these be remade to CentOS, too?
