### ISSUE TITLE
Introduction pages specific to audience (roles)

### ISSUE THREAD

**Issue by piogor** [tango-controls/tango-doc#105]
Following (#50) labelling (#104) of documents a pages pointing to documents for different audience roles (beginners, developers,  users, administrators) should be created.

**Comment by PhilLAL** [comment]
I copy here the content of issue #226 which is on the same topic.
Not sure this suggestion is the best one. ;)


1. Following #50 and #104 it's not clear different targets administrators, users, and developers are on the same level as beginners, all.

administrators, users, and developers should be roles whereas beginners (and possible other) are levels.

2. Another issue is that several long pages can be found through the search bar and users can arrive on a section without being conscient that the page targets another role or level.

To solve 1. this, one could use some headers into the doc to understand at a glance who is the target.
It could be a colored header for the level, and a figure for the roles.
To solve 2. the header should be always visible.
