### ISSUE TITLE
Integrate PyTango documentation

### ISSUE THREAD

**Issue by andygotz** [tango-controls/tango-doc#12]
PyTango has been sphinxed since a long time and is avilable online here 

    http://pytango.readthedocs.io/en/latest/

It must be linked to the tango-controls documentation at least via a link but probably by referring to the source somehow. The source is here

    https://github.com/tango-controls/pytango/tree/develop/doc

**Comment by LJBD** [comment]
We should ask @vxgmichel or @tiagocoutinho to contribute to the documentation on how to use threads with PyTango.

**Comment by vxgmichel** [comment]
I think it's better to keep the tango-controls and pytango docs separated (for several technical and non-technical reasons I can enumerate if necessary). A simple section with some links and examples from the pytango ecosystem should work out. What do you guys think?

**Comment by LJBD** [comment]
I think that it's all right to keep it separate, at least for now. Maybe in the future, if the implementations will be exactly the same, we will have a good reason to integrate it completely.
For now, I will just refer to it as it is and afterwards we will work on some examples.
