### ISSUE TITLE
Layered map for Developer Tools out of documenation layout

### ISSUE THREAD

**Issue by piogor** [tango-controls/tango-doc#120]
See: 
![obraz](https://user-images.githubusercontent.com/9037672/30037736-0be3387c-91be-11e7-803e-53dbb218d1d7.png)
I am not sure if there is an easy way to make it fit.

**Comment by andygotz** [comment]
I can put it in a scrolled window if you think that is better. The other option is to split it in two. I will discuss with Stuart how best to solve this.

**Comment by chedburgh** [comment]
I can split it in two if you want. Keep the java stack in one diagram and
rest in another.

**Comment by andygotz** [comment]
Splitting sounds like a good idea.

**Comment by chedburgh** [comment]
So, I looked at that on my mobile, the page was formatted well for mobile
device, but the diagrams far to wide. Perhaps it's worth using a scroll box
on top of splitting the diagram?

I will see what I can find out about using relative paths, it would help us
maintain links better as the documentation changes!

**Comment by Ingvord** [comment]
IMHO these diagrams should go into *tools and extensions* it there the place where you first look for a tool if you look for a tool, not *Tango overview*. Perhaps here simple text would be enough and a link to tools.

**Comment by Ingvord** [comment]
This text must be more about Tango Community, that it has different projects on top of Tango library + describe how it is organized i.e. forum, sourceforge, github etc. Tango Collaboration contract etc

**Comment by chedburgh** [comment]
Added a pull request that splits the diagram.

**Comment by andygotz** [comment]
Problem fixed. Map split into 2 sections.
