### ISSUE TITLE
Undefined reference to chapter 1.6.5 in DS Guidelines

### ISSUE THREAD

**Issue by MikeFalowski** [tango-controls/tango-doc#126]
In subsection about commands in [DS Guidelines](tango-doc/source/development/device-api/ds-guideline/TangoDesignGuidelines-Revision-7.rst) there is reference to chapter 1.6.5

> State: enumeration, representing the different states described in chapter 1.6.5. 

I can't find such chapter, is it from old documentation?

Maybe it should point here http://tango-controls.readthedocs.io/en/latest/overview/SimplifiedTangoDatamodel.html?highlight=state

**Comment by andygotz** [comment]
Thanks for pointing this out. Actually it should point to the Device States. There are many cross references which are wrong. I am busy fixing them.
