### ISSUE TITLE
JDraw/Synoptic manual

### ISSUE THREAD

**Issue by piogor** [tango-controls/tango-doc#13]
The JDraw and Synpotic manual exists as part of ATK documentation but it will be good to have it documented separately as other tools.

**Comment by LJBD** [comment]
That manual should be included in End User documentation.

**Comment by piogor** [comment]
@lzytniak, please convert a JDraw section of the document sent by Faranguiss.

**Comment by piogor** [comment]
[Tutorials.docx](https://github.com/tango-controls/tango-doc/files/976731/Tutorials.docx)
