### ISSUE TITLE
Add a link to JTango reference

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/tango-doc#134]
As we now host JTango JavaDoc on javadoc.io: http://javadoc.io/doc/org.tango-controls/JTangoServer/10.0.0

A link to it must be added to the documentation

**Comment by piogor** [comment]
Should it be placed somewhere on the map (http://tango-controls.readthedocs.io/en/latest/development/overview.html#java) ?

**Comment by piogor** [comment]
Hi @Ingvord, is it duplication of #111?

**Comment by Ingvord** [comment]
@piogor , yes. It is a duplicate
