### ISSUE TITLE
missing states into some part of the doc

### ISSUE THREAD

**Issue by PhilLAL** [tango-controls/tango-doc#143]
I noticed there are two parts in the doc which seems to miss some states:
- https://github.com/tango-controls/tango-doc/blob/master/source/development/device-api/ds-guideline/device-server-guidelines.rst#states-choice
- https://tango-controls.readthedocs.io/en/latest/reference/glossary.html#glossary

I completed the last one with #142 but would not know how to complete first one.

**Comment by piogor** [comment]
Hi, Thank you. Sorry for late answer. I will merge the pull request #142.
I can't see any missing states in the first one.

**Comment by PhilLAL** [comment]
No problem Piotr. I just saw that you assigned this PR to you while I was just creating a new branch to make it clean and closing  #142 

For the first one, you're right, I am not sure to remember but I probably meant that the first list was more complete than second one.

**Comment by PhilLAL** [comment]
I had that for first one (https://github.com/tango-controls/tango-doc/blob/master/source/development/device-api/ds-guideline/device-server-guidelines.rst#states-choice) states can be gathered according to 2 logic:
- by couple of opposite state (open/close, on/off, etc.)
- by couple of similar state: 
  * open, on, insert for active states
  * close, off, extracting, disable for unactive states
  * unknown, alarm, fault for sort of "invalid" states
  * init, standby, moving, running for temporary states

The current list use both logics. Perhaps states could be gathered according to the same logic, but I wondered which one is more relevant...

**Comment by piogor** [comment]
Hi, what about the following order:
INIT, STANDBY, DISABLE, ALARM, FAULT, UNKNOWN, ON, OFF, OPEN, CLOSE, INSERT, EXTRACT, MOVING, RUNNING?
It is build upon the following logic: first general ones, error related ones then couples.

**Comment by bourtemb** [comment]
The order which was given in PR #142 is the one from the enum declaration in tango.idl file so it could also help to identify the corresponding value of each state. Keeping this order could be useful for that.

**Comment by PhilLAL** [comment]
Indeed Reynald, it will be better to keep the same order than the enum in [tango.idl](https://github.com/tango-controls/tango-idl/blob/master/tango.idl).
The order has to be modified just into https://github.com/tango-controls/tango-doc/blob/master/source/development/device-api/ds-guideline/device-server-guidelines.rst#states-choice it is already good into https://tango-controls.readthedocs.io/en/latest/reference/glossary.html#glossary

**Comment by piogor** [comment]
Oh, I see. Then, @PhilLAL , will you update the table accordingly in https://github.com/tango-controls/tango-doc/blob/master/source/development/device-api/ds-guideline/device-server-guidelines.rst#states-choice
or do you prefer me to do it?

**Comment by PhilLAL** [comment]
I just pushed #152 to correct this.

**Comment by piogor** [comment]
It seems this is done... Thanks @PhilLAL , I am closing the issue.
