### ISSUE TITLE
Bensikin documentation in sphinx

### ISSUE THREAD

**Issue by piogor** [tango-controls/tango-doc#15]
Snapshot tool documentation is attached to the package but it will be good to include it in common repository, too.

**Comment by LJBD** [comment]
It should be split into two parts: installation/deployment (included in DevOps part of documentation) and Bensikin manual (included in End User part).

**Comment by piogor** [comment]
The task has been split into two - this one (almost completed) and administrator part  ( #154, to be done).

**Comment by piogor** [comment]
#155 has been merged so the task is going to be closed. If there are any changes required, the new issue may be opened :-) .
