### ISSUE TITLE
Requirments for Tango controls

### ISSUE THREAD

**Issue by piogor** [tango-controls/tango-doc#162]
Provide information what is needed to make Tango work correctly in all aspects

**Comment by piogor** [comment]
This may be a paragraph of this document:
https://tango-controls.readthedocs.io/en/dev/installation/minimum-deployment.html

**Comment by PhilLAL** [comment]
Possible information sources:
- astroblogweb installation script: https://github.com/astroblogweb/tangocs/blob/master/tango_install/tango_installation.sh
- Ubuntu installation video (Ubuntu 14.04 LTS, Ubuntu 14.04, Mint 17): https://www.youtube.com/watch?v=f903EIbiv6w
- ThomX installation script: https://gitlab.in2p3.fr/CCThomX/installation/blob/master/script-install.sh
- dedicated doc page https://tango-controls.readthedocs.io/en/dev/installation/index.html

Sections to (re)move:
- https://tango-controls.readthedocs.io/en/dev/installation/tango-on-windows.html#what-is-tango-controls scope is more general than windows, it should be moved into https://tango-controls.readthedocs.io/en/dev/installation/minimum-deployment.html

**Comment by PhilLAL** [comment]
Several parts of installation/tango-on-windows.html could be moved into installation/requirements since they're not specific to windows.

**Comment by PhilLAL** [comment]
Should add non-interactive steps to install MariaDB on GNU/Linux

**Comment by PhilLAL** [comment]
Instructions to add astor adding host are present in https://tango-controls.readthedocs.io/en/dev/installation/tango-on-windows.html and in https://tango-controls.readthedocs.io/en/dev/tools-and-extensions/astor/add_host.html
Should add redirection from https://tango-controls.readthedocs.io/en/dev/installation/tango-on-windows.html to https://tango-controls.readthedocs.io/en/dev/tools-and-extensions/astor/add_host.html to avoid redundant information

**Comment by PhilLAL** [comment]
Solved by #230
