### ISSUE TITLE
REST API documentation has to be integrated into the documentation

### ISSUE THREAD

**Issue by andygotz** [tango-controls/tango-doc#17]
We need to integrate the mtango documentation into the global documentation either as a link to this:

    https://bitbucket.org/hzgwpn/mtango/wiki/mTango%20REST%20API

OR by converting it to Sphinx.

**Comment by LJBD** [comment]
According to #1, this should be in Tango Ecosystem ( #40 ) and in Tango Developer -> Client API -> REST API.

**Comment by Ingvord** [comment]
Done in #43
