### ISSUE TITLE
ATKPanel manual disappeared

### ISSUE THREAD

**Issue by PhilLAL** [tango-controls/tango-doc#176]
Page https://tango-controls.readthedocs.io/en/latest/tools-and-extensions/atk/atkpanel.html seems to appear in research results on ATKPanel keyword, it should probably link to https://tango-controls.readthedocs.io/en/latest/tools-and-extensions/atk/index.html.
Am I wrong ?

Whatever, a full search on this link shows that it only appears in the page source/getting-started/end-user/index.rst so correction will be simple if needed.

**Comment by piogor** [comment]
It duplicates #42 ..

**Comment by PhilLAL** [comment]
exact, sorry :)
