### ISSUE TITLE
Bindings documentation to be integrated

### ISSUE THREAD

**Issue by andygotz** [tango-controls/tango-doc#18]
There are a number of bindings to different products like matlab, labview, igorpro, etc. How to integrate these into the sphinx documentation? I am not sure these documents are even online. they are part of the binding itself. To be studied.

**Comment by LJBD** [comment]
According to #1, those should be referenced in the Tango Ecosystem ( #40 ) and it would be good if some how-tos were supplied as well.
Also, there is a new version of the "layer map" (tracked by #28) that includes some links to the bindings.

**Comment by chedburgh** [comment]
At the minimum we could move the information from [here](http://www.tango-controls.org/downloads/bindings/) to [here](http://tango-controls.readthedocs.io/en/latest/tools/index.html#bindings). This would keep the map in sync with the documentation since it now points to that new location.

**Comment by andygotz** [comment]
Good idea. I would suggest that we suppress the web page on the tango-controls site to avoid having to maintain two copies.

Could you try to integrate the map into the documentation using the html version so it is clickable.

Thanks!
