### ISSUE TITLE
Layout redesign

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/tango-doc#2]
I think it is better if we switch to classical layout i.e. ToC on the left hand side with index search on top of it. Content on the right hand side with header, where header is the current part of the documentation + breadcrumbs and left and right navigation links.  See sketch below:

![layout](https://cloud.githubusercontent.com/assets/11678364/25127292/9fe84f0e-2435-11e7-8f05-849760f8a9ed.png)

Note that the color scheme is just an example.

Source file for image is attached: 
[Layout.odg.zip](https://github.com/tango-controls/tango-doc/files/928790/Layout.odg.zip)

**Comment by LJBD** [comment]
From the discussion during the first day of the Write-the-doc camp:
1. The theme looks outdated and should be changed to a more modern one. 
2. The colours of the links should not be the same as those of headers.
3. It would be great to have separate indices of various things.
4. Table of contents should be responsive and searchable.

**Comment by andygotz** [comment]
WTD participants agreed to move to ReadTheDocs theme but change the colour to Tango green.

**Comment by piogor** [comment]
The branch td-2-new-theme there is the version with rdt theme (not yet updated). It is included as a git subtree linking to the barnch `tango-cs-rtd-theme` of @piogor fork of the original theme. See: https://github.com/piogor/sphinx_rtd_theme/tree/tango-cs-rtd-theme.

**Comment by piogor** [comment]
The branch is built as protected (accessible only if one have a link) on readthedocs: http://tango-controls.readthedocs.io/en/td-2-new-theme/index.html

**Comment by LJBD** [comment]
It looks really nice! Have you tired replacing blue elements with green ones (like the logo background in the top left corner)?

**Comment by piogor** [comment]
The work is in progress. Now I am learning SASS (http://sass-lang.com/) which is used by RtD theme to provide styling...

**Comment by andygotz** [comment]
I agree with Lukasz the result is very nice and pleasing to read - well done!

**Comment by piogor** [comment]
It seems that it is not enough to change CSS of the `sphinx_rtd_theme` placed in the documentation `_theme` folder  like for other themes. It works locally but not on the RtD. There are some tricks used at readthedocs servers (https://blog.deimos.fr/2014/10/02/sphinxdoc-and-readthedocs-theme-tricks-2/). So, t the branch td-2- will be removed and new one will be created with the trick applied.

**Comment by piogor** [comment]
It seems that it is not enough to change CSS of the `sphinx_rtd_theme` placed in the documentation `_theme` folder  like for other themes. It works locally: 
![rtd-green](https://cloud.githubusercontent.com/assets/9037672/26489134/6fb4f276-4206-11e7-998a-0a53ca6383c7.png)

but not on the RtD. There are some tricks used at readthedocs servers (https://blog.deimos.fr/2014/10/02/sphinxdoc-and-readthedocs-theme-tricks-2/). So, the trick will be applied.

**Comment by piogor** [comment]
The new them is applied to the master. The issue is going to be closed.
