### ISSUE TITLE
snapshots Astor doc update for events

### ISSUE THREAD

**Issue by PhilLAL** [tango-controls/tango-doc#203]
Hi,
I recently noticed that some snapshots are old and still propose "Use events" instead of "Manage notifd", like in https://tango-controls.readthedocs.io/en/latest/tools-and-extensions/astor/add_host.html#add-a-new-controlled-host

There are probably some other snapshots not up-to-date, which can not be checked by regexp search.
Perhaps we could use this issue to list them?

Regards.

**Comment by piogor** [comment]
It is duplicated in #222. As the #222 contains this and is in progress now. I am closing this task to avoid double reporting.
