### ISSUE TITLE
Add LogViewer documentation

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/tango-doc#21]
- how to use
 - how to setup
etc

**Comment by LJBD** [comment]
According to #1, LogViewer documentation should be put in the End User part of the documentation.

**Comment by piogor** [comment]
The pull request #183 by @daneos as been merged. 
- [ ] However, it would be nice to add some short paragraph about how the logging works (things like there is a device started as logging target and so) - just two sentences and reference to the following chapter: https://tango-controls.readthedocs.io/en/latest/development/advanced/reference.html?highlight=log#the-device-logging. (as :ref:More details about logging service <the-device-logging>).

**Comment by piogor** [comment]
#193 by @daneos, made this issue done.
