### ISSUE TITLE
empty section to complete

### ISSUE THREAD

**Issue by PhilLAL** [tango-controls/tango-doc#219]
Here is a list of empty sections which should be completed: 

- [ ] https://tango-controls.readthedocs.io/en/latest/installation/pytango-and-taurus-on-windows.html
- [ ] https://tango-controls.readthedocs.io/en/latest/getting-started/development/java/jtango-client.html

**Comment by HelgaMond** [comment]
» Administration » Maintenance
Maintenance
https://tango-controls.readthedocs.io/en/dev/administration/maintenance/index.html

**Comment by HelgaMond** [comment]
» Tutorials and How-Tos » HOW-TOs » How to distinguish clients on the server side
CPP and Python sections to do 
https://tango-controls.readthedocs.io/en/latest/tutorials-and-howtos/how-tos/how-to-distinguish-clients-on-the-server-side.html

» Tutorials and How-Tos » HOW-TOs » Using Tango servers without DB for unit testing
CPP and Python sections to do 
https://tango-controls.readthedocs.io/en/latest/tutorials-and-howtos/how-tos/how-to-use-tango-servers-without-db.html

**Comment by HelgaMond** [comment]
» Tools and Extensions » Astor (TANGO Manager) » New Server Wizard
New Server Wizard is missing
https://tango-controls.readthedocs.io/en/dev/tools-and-extensions/built-in/astor/index.html

**Comment by HelgaMond** [comment]
Dedicated issues were created for each link/part: #234 #235 #236 #237 #238 #239 #240 #241 #242
