### ISSUE TITLE
Add Starter documentation

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/tango-doc#22]
- how to use
 - how to setup
etc

**Comment by LJBD** [comment]
According to #1, Starter documentation should go to the DevOps part of the documentation.

**Comment by piogor** [comment]
This should be a document within `administration/deployment`

**Comment by PhilLAL** [comment]
Perhaps to uniformize with [Astor explanations](https://tango-controls.readthedocs.io/en/latest/tools-and-extensions/astor/index.html) to avoid redundant informations.

Another way could be to split Astor doc into a developer part (with astor) and an administrator part (with starter installation and configuration).
