### ISSUE TITLE
"Tools and Extensions" menu part misses submenus (Built-in tools, Archiving, GUI building ...)

### ISSUE THREAD

**Issue by HelgaMond** [tango-controls/tango-doc#223]
The main menu (on the left of the documentation) is not consistent with one on the "Tools and Extensions" page. Perhaps we should add submenus (Built-in tools, Archiving, GUI building, Bindings, Other tools) to the main menu of the "Tools and Extensions".

**Comment by piogor** [comment]
The PR #228 fixes this issue. Closing.
