### ISSUE TITLE
Move how to work with the documentation section into wiki of this repo

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/tango-doc#24]
IMHO it should go into the project's wiki on GitHub rather then into the documentation itself. Not critical of course but would be more logical to put it into the [Contribution page](https://github.com/tango-controls/tango-doc/wiki/Contribution)

**Comment by LJBD** [comment]
In #55 README has the links to documentation overview and the workflow tutorial. I guess that accepting that should close this issue.
