### ISSUE TITLE
TANGO logo doesn't lead to the Welcome page

### ISSUE THREAD

**Issue by HelgaMond** [tango-controls/tango-doc#247]
Perhaps, it would be more logical to have the "Welcome to Tango Controls documentation" page instead of duplicating table of contents when clicking on TANGO logo.

**Comment by PhilLAL** [comment]
Hi Helgo,
I'm not sure which link do you talk about, could you give the page on which is the link and logo, the current URL to which it links, and the URL you suggest for this link? :)

**Comment by piogor** [comment]
@HelgaMond, it is the default behaviour of the theme. I think it is ok but I could be wrong ;-).

**Comment by piogor** [comment]
@HelgaMond, I am closing this issue as `wontfix`. However, feel free to reopen it if you find it important. I have marked it `wontfix` mostly because this is related to the theme and it may provide difficulties in maintenance if we change the default behaviour.
