### ISSUE TITLE
Searching is now broken

### ISSUE THREAD

**Issue by stanislaw55** [tango-controls/tango-doc#256]
Hello,
I don't know why but recently searching in documentation returns list of references to different projects. This is real pain because one cannot easily search Tango related stuff. I've tried searching 'callback' and it printed out list of references to projects like pywayland which I believe is not part of Tango ecosystem. 

I've this [link](https://tango-controls.readthedocs.io/en/latest/tutorials-and-howtos/index.html) to documentation.

**Comment by piogor** [comment]
@stanislaw55, thanks for reporting.
It iss trange, what web browser do you use? 
With my firefox I get this result:
![obraz](https://user-images.githubusercontent.com/9037672/52855618-363b0f00-3122-11e9-8f9f-67c7855e4640.png)

**Comment by stanislaw55** [comment]
I use Opera but check just now Firefox and the result is the same. I used [this](https://tango-controls.readthedocs.io/en/latest/) link. Here is my output.
![image](https://user-images.githubusercontent.com/32959446/52855801-c9744480-3122-11e9-870a-28824ac73751.png)

As you see, this prints project that I guess are not related to Tango. Maybe I have wrong link? That is **latest** version if it's relevant.

**Comment by stanislaw55** [comment]
Ok I got this: latest version prints those unrelated projects but dev doesn't. I don't know how does relates to branching flow but I think it's connected to branches.

**Comment by piogor** [comment]
After making the latest being the default the search works correctly. @stanislaw55, thanks again. I am closing the issue.
