### ISSUE TITLE
Reworking Getting Started

### ISSUE THREAD

**Issue by LJBD** [tango-controls/tango-doc#26]
Getting started should be reworked to really reflect newbies needs.
It should include:
1. Examples
2. Authentication&Authorisation

Afterwards, we should also define possible use cases.

**Comment by LJBD** [comment]
According to #1, this should be included somewhere in the Beginner Tango Developer part of the documentation.

**Comment by piogor** [comment]
@HelgaMond, I have moved "Getting Started" related chapters to the new structure in a branch [td-50-structure-toc-rework](https://github.com/tango-controls/tango-doc/tree/td-50-structure-toc-rework) (as part of #50 ). So, if you will work on it please use this branch as a base.
