### ISSUE TITLE
Mark the 9.3 release

### ISSUE THREAD

**Issue by piogor** [tango-controls/tango-doc#276]
It is nice to reflect the current release of Tango in the documentation.
- [x] version update in conf.py (after #273)

Then, when source distribution is ready:
- [ ] tag 9.3.3 as a stable release

**Comment by piogor** [comment]
@Ingvord, @gwen-soleil, @lorenzopivetta, @Pascal-Verdier, @t-b, @mliszcz, @chedburgh, @bourtemb, @andygotz, are there any important updates to the documentation, which need to be implemented before tagging 9.3.3?

**Comment by bourtemb** [comment]
I would use a branch rather than a tag for 9.3.3 documentation because we want this documentation to be able to evolve and to receive contributions to improve it in the future.

**Comment by mliszcz** [comment]
@bourtemb, I've just created 9.3.3 branch.
@piogor I think we can close this issue now.

**Comment by t-b** [comment]
I've created the 9.3.4 branch off from the 9.3.3 branch.

**Comment by bourtemb** [comment]
> I've created the 9.3.4 branch off from the 9.3.3 branch.

@t-b, from what @mliszcz suggested [here](https://github.com/tango-controls/cppTango/issues/594#issuecomment-544832023), it seems we should rather create 9.3.4 branch from the master branch.

**Comment by t-b** [comment]
@bourtemb 9.3.3 is at the same commit as master.

```$git nn 9.3.3
7f4829d8 (Merge pull request #301 from mliszcz/add-authors-2nd-write-the-doc-camp, 2019-10-08)
firma@thomas:~/devel/tango-doc (9.3.4)
$git nn master
7f4829d8 (Merge pull request #301 from mliszcz/add-authors-2nd-write-the-doc-camp, 2019-10-08)
```

so this is by accident already the desired state or?

**Comment by bourtemb** [comment]
> so this is by accident already the desired state or?

Yes, it looks like: https://github.com/tango-controls/tango-doc/compare/9.3.3...9.3.4
https://github.com/tango-controls/tango-doc/compare/master...9.3.4
