### ISSUE TITLE
Review of the "layer map" of Tango

### ISSUE THREAD

**Issue by LJBD** [tango-controls/tango-doc#28]
There is a [map of Tango-related tools](http://www.tango-controls.org/resources/documentation/map/) which might be a bit outdated. We should check how the tools have changed and if they have a reference in the documentation.

**Comment by chedburgh** [comment]
Attaching an updated map. Split into 5 diagrams.

Binding appears to be out of date, there are several new bindings at http://www.tango-controls.org/downloads/bindings.

[updated_tango_map.zip](https://github.com/tango-controls/tango-doc/files/973563/updated_tango_map.zip)

**Comment by chedburgh** [comment]
Following document lists the items we found missing a link or having documentation outside readthedocs.

[missing.pdf](https://github.com/tango-controls/tango-doc/files/973760/missing.pdf)

**Comment by Ingvord** [comment]
Cool! Once we have splitted maps we can think of improving them. What comes into my mind is to put high level boxes on top of a specific language Device API/Client API e.g. ATK should be on top of Client Java API; Sardana on top of PyTango etc. This way it will reflect much more accurately the technology stack.

**Comment by chedburgh** [comment]
Quick example for above:

![tango_control_system_development_alt1_1](https://cloud.githubusercontent.com/assets/4125258/25668652/369fdd14-301f-11e7-9d28-8dc94031a7b2.png)

**Comment by Ingvord** [comment]
Could you please add REST API to the diagrams:

in bindings: REST API on top of Device API; HTTP protocol on top of REST API box


in control system development: REST API on top of Device API; mtangorest.server ([link](https://bitbucket.org/hzgwpn/mtangorest.server)); 3 boxes on top of mtangorest.server: mTangoSDK ([link](https://bitbucket.org/hzgwpn/mtango/wiki/Home)), tango-js ([link](https://tangojs.github.io/)); JYSE studio (no link)

**Comment by chedburgh** [comment]
The modified diagrams look as follows:

![tango_bindings_map1_1](https://cloud.githubusercontent.com/assets/4125258/25710706/ecbd544e-30e4-11e7-87df-617eed7ba471.png)
![tango_control_system_development_alt1_1](https://cloud.githubusercontent.com/assets/4125258/25710709/f098be64-30e4-11e7-9a49-23f05bd6df9d.png)

**Comment by chedburgh** [comment]
Adding the current state of the map diagrams for reference.
[tango_bindings_map.zip](https://github.com/tango-controls/tango-doc/files/976777/tango_bindings_map.zip)

**Comment by andygotz** [comment]
REST-API is always http so I don't think it is necessary to put it on the diagram. I just had an exchange with Igor and he accepts my proposal to remove "HTTP protocol" from the bindings layer map. Could you remove it Stuart? Thanks.

**Comment by Ingvord** [comment]
I have a comment for control system development diagram - mtangorest.server must be directly on top of DeviceAPI - it does not use ATK. Thanks!

**Comment by chedburgh** [comment]
I will make the changes shortly, then add them to a branch. I will not create a pull request, since we may want to modify the diagrams more.

**Comment by chedburgh** [comment]
Updated the diagrams based on feedback above. Added a pull request to merge in the html/png files into source/_static/layer-map-source.

Pull request: #82

**Comment by chedburgh** [comment]
#82

**Comment by chedburgh** [comment]
I think it would be a good idea to store the source files for the layer maps in the repo somewhere?

**Comment by Ingvord** [comment]
@chedburgh I usually store source files next to the exported ones

**Comment by chedburgh** [comment]
Sounds good to me then. I will add them. I will keep this ticket open, since I want to update the links in some of the maps.

**Comment by chedburgh** [comment]
I have update the links in the 4 diagrams as best I can with the new documentation. Nearly all point to something relevant now. I will create a pull request and keep this open for any feedback and future changes.
