### ISSUE TITLE
Broken link to download TangoBox 9.3

### ISSUE THREAD

**Issue by sblanchet** [tango-controls/tango-doc#296]
In the [virtual machine instructions](https://tango-controls.readthedocs.io/en/latest/installation), the link to download TangoBox 9.3 is broken. 

The actual link targets an invalid SharePoint document at [s2innovation.com](http://s2innovation.com).

Maybe it would be safer to link directly a file on the [ESRF FTP server](http://ftp.esrf.fr/pub/cs/tango/) as TangoBox 9.2 did.

**Comment by bourtemb** [comment]
> In the [virtual machine instructions](https://tango-controls.readthedocs.io/en/latest/installation), the link to download TangoBox 9.3 is broken.

It does not seems to be broken to me... Can you be a bit more precise about the location of the broken link?

**Comment by sblanchet** [comment]
You are right:  the webpage was blocked by NoScript in my Firefox session.
After allowing Javascript from sharepoint.com and many other domains, I can finally reach the download page.
