### ISSUE TITLE
Polish for new release

### ISSUE THREAD

**Issue by t-b** [tango-controls/tango-doc#365]
- [x] Remove wrong patch link in https://tango-controls.readthedocs.io/en/latest/installation/patches.html#version-9-1-0-source-patches
- [x] Remove references to old sourceforge release, replace with newer github releases
- [x] Rework windows binary section
- [x] Raise copytight year

@ajoubertza I've seen that the python package links at the bottom  of https://tango-controls.readthedocs.io/en/latest/installation/binary_package.html are all broken. I can correct them if you like and tell me the right ones. Or should we remove it and link to a place which fits better?

**Comment by ajoubertza** [comment]
> @ajoubertza I've seen that the python package links at the bottom of https://tango-controls.readthedocs.io/en/latest/installation/binary_package.html are all broken. I can correct them if you like and tell me the right ones. Or should we remove it and link to a place which fits better?

@t-b Yes, please correct them.  For Windows the official place to find the binaries is now PyPI, so can you add a link and a badge for that?  https://pypi.org/project/pytango/. For the badge, the pytango repo readme has the source.

Unfortunately the latest release, 9.3.2, is broken for Windows, so 9.3.1 should be used instead.  It would be nice if the tango-doc repo didn't need updating for each PyTango release, so we probably shouldn't mention any versions. 

I'm not aware of a good source for binary Linux packages, but we do have Conda binary packages now:  https://anaconda.org/tango-controls/pytango.

You might also want to add links to the other projects that have Conda packages:  https://anaconda.org/tango-controls/repo.  The https://anaconda.org/tango-controls/tango package is no longer being updated.  It contained many cppTango related things + dependencies, but has been split into smaller packages:  tango-idl, cpptango, tango-test.

**Comment by t-b** [comment]
@ajoubertza Thanks. I've removed most of the versions and just badges instead. The binary page is now also much cleaner.
