### ISSUE TITLE
Documentation of the Tango Ecosystem

### ISSUE THREAD

**Issue by LJBD** [tango-controls/tango-doc#40]
The Tango Ecosystem should have a dedicated section in the documentation. From what we've decided, it should be for Contributors and the following issues should be addressed:
1. Sourceforge/SVN projects ([tango-cs](https://sourceforge.net/projects/tango-cs/) and [tango-ds](https://sourceforge.net/projects/tango-ds/)).
2. GitHub/Git organisation and projects ([tango-controls](https://github.com/tango-controls)).
3. [Website](http://www.tango-controls.org) and the [forum](http://www.tango-controls.org/community/forum/) there.
4. External projects using Tango
4.1. Commercial software bindings:
4.1.1. Matlab
4.1.2. LabView
4.1.3. IgorPro
4.2. Other bindings:
4.2.1. [REST API](https://github.com/tango-controls/rest-api)
4.2.2. [TangoJs](https://github.com/tangojs)
4.3. Sardana
4.4. Fandango
4.5. SimulatorDS
4.6. HDB/TDB archiving
4.7. SNAP
4.8. HDB++ archiving
... and any other projects that one can think of (especially those that are included in tango-controls organisation on GitHub).

Also, we've talked about where to keep that piece of documentation. I believe that the general consensus is that we should keep the descriptions of the projects on the website. In the documentation we'll just put a list of the external projects (as well as more detailed descriptions of the first 3 points from the list above) and include links to dedicated parts of the website.

This is directly related to #1.

**Comment by piogor** [comment]
As the ecosystem is there: https://tango-controls.readthedocs.io/en/latest/overview/ecosystem.html
The task is ready to be closed.

@HelgaMond, @andygotz, @bourtemb, @t-b, @mliszcz, @Ingvord, I am cleaning the issues closing the ones I found either resolve or invalid. Feel free to reopen if you find I made a mistake.
