### ISSUE TITLE
Integrate tutorials with the documentation

### ISSUE THREAD

**Issue by LJBD** [tango-controls/tango-doc#46]
There are [tutorials](http://www.tango-controls.org/resources/tutorials/) on the website and they should be integrated in the documentation.
For now we can just link the presentations, but in the future it would be great to fully integrate their contents with Sphinx.
According to #1, every tutorial should be marked with an appropriate level of expertise in Tango.

**Comment by piogor** [comment]
It is already done in section https://tango-controls.readthedocs.io/en/dev/tutorials-and-howtos/tutorials/index.html  so I am closing the task.
