### ISSUE TITLE
Rework documentation structure.

### ISSUE THREAD

**Issue by LJBD** [tango-controls/tango-doc#50]
The idea is to have table of contents split into several main headings and, at the same time, refer to specific roles and be able to generate indices for them.

**Comment by LJBD** [comment]
We've created a specification of the new documentation structure.
[tango-doc-structure.docx](https://github.com/tango-controls/tango-doc/files/976141/tango-doc-structure.docx)

**Comment by piogor** [comment]
You may preview the new structure here: http://tango-controls.readthedocs.io/en/td-50-structure-toc-rework/contents.html

**Comment by piogor** [comment]
The structure is reworked and merged into master.
