### ISSUE TITLE
Move photos of tango dancers to reference

### ISSUE THREAD

**Issue by andygotz** [tango-controls/tango-doc#77]
I propose to move the photos of the tango dancers to a reference section. It find they do not add much to the text and are a bit out of place sometimes. Someone once said they take up a lot ink on the printer.

Another option is to convert them to thumbnails and link them to a high-res version on the website.

Opinions - for or against? I wait for your feedback before doing anything.

Andy

**Comment by piogor** [comment]
@andygotz, I think is is no longer releveant as "the manual" is no longer there. Closign the issue.
