### ISSUE TITLE
move HDB++ documentation from tango-controls website

### ISSUE THREAD

**Issue by andygotz** [tango-controls/tango-doc#78]
Move the documentation on the tango-controls website here http://www.tango-controls.org/community/projects/hdbplus/ to sphinx and integrate it into the tango-doc repository.

**Comment by lzytniak** [comment]
Is there available "HDB++ Design and implementation" (http://www.tango-controls.org/media/filer_public/01/76/0176d2dd-05bc-4ee0-ab84-5ba22436f02b/hdb-design-guidelines-18.pdf) in docx or different format?

**Comment by LJBD** [comment]
Maybe @bourtemb or @gscalamera know something about it?

**Comment by andygotz** [comment]
I reckon they should know. I cannot find it either.

**Comment by gscalamera** [comment]
I don't have the sources of the design guidelines document.
Lorenzo Pivetta have them and if I remember well they could be in LaTeX.

**Comment by bourtemb** [comment]
As Graziano said, this document was generated from a LaTeX file:
https://sourceforge.net/p/tango-cs/code/HEAD/tree/archiving/hdb++/doc/hdb++-design-guidelines/trunk/hdb%2B%2B-design-guidelines.tex
I remember Lorenzo said he was considering moving it to sphinx but it didn't know when he could do it... I guess he didn't have time to do it.

**Comment by chedburgh** [comment]
Not sure how helpful this is, but I just converted it to an rst file via pandoc. See attached. I do not have time to check how it looks in the documents (not set up to build it here), so perhaps the layout is not perfect?

Converting it using pandoc:

pandoc --from=latex --to=rst --output=hdb++-design-guidelines.rst  hdb++-design-guidelines.tex

Maybe helpful for future documents if not this one?

[hdb++-design-guidelines.zip](https://github.com/tango-controls/tango-doc/files/989168/hdb.-design-guidelines.zip)

**Comment by gscalamera** [comment]
Lorenzo gave me the LaTeX sources of the last release of the documentation that is the 1.8 (while 1.7 is on sourceforge)

**Comment by andygotz** [comment]
Great to see this advancing! Can you reprocess the latex to rst following Stuart's recipe? Then it needs to be inserted into the tango-doc repository.

**Comment by gscalamera** [comment]
There are some issues with that:
- \hdb{} and \tango{} disappear in the conversion so no HDB++ and no TANGO words in the converted file
- toc is skipped (maybe that is ok?)
- HdbConfigurationManager.pdf and HdbEventSubscriber.pdf are the pogo-generated documentation of the 2 device servers and are included as pdf in the design guidelines document, but I can re-generate the html with pogo for that
[hdb++-design-guidelines.tar.gz](https://github.com/tango-controls/tango-doc/files/989778/hdb.-design-guidelines.tar.gz)

**Comment by lzytniak** [comment]
@gscalamera Could you please generate html version for HdbConfigurationManager and HdbEventSubscriber and upload?

**Comment by gscalamera** [comment]
Hi,
I've just generated the html of the latest hdbpp-es and hdbpp-cm.
Note that the rest of the document is a bit outdated compared to these (new commands and attributes for ttl handling are missing) but I think it shouldn't be a problem for now. @bourtemb do you agree?
Note also that I attached the whole doc_html directories but I think just the FullDocument.html file was used for the pdf version.
[hdbpp-es_doc_html.tar.gz](https://github.com/tango-controls/tango-doc/files/1018132/hdbpp-es_doc_html.tar.gz)
[hdbpp-cm_doc_html.tar.gz](https://github.com/tango-controls/tango-doc/files/1018134/hdbpp-cm_doc_html.tar.gz)

**Comment by bourtemb** [comment]
Hi,
I think we should prepare a documentation for the coming release of HDB++, which will support TTL feature. We will have to update the obsolete documents. So I think it's a good idea to put the latest version of the documentation for HdbConfigurationManager and HdbEventSubscriber device servers. This is a good starting point.

**Comment by lzytniak** [comment]
For future reference, it took me some time to convert html to rst file and still it is not perfect. Maybe someone has a better idea?
First, I tried my script using pandoc:
https://github.com/lzytniak/cfg-pandoc-html2rst/blob/master/html2rst.sh
but the result was not good.
Next, I found html2rest (https://pypi.python.org/pypi/html2rest), result was a little better.
Someone on stackoverflow suggested to open the resulting HTML file in LibreOffice Writer, and (after a little editing) Save As any other document format you like.

I opened FullDocument.html in Word, I saved it as docx and then I converted it to rst file
https://ronn-bundgaard.dk/blog/convert-docx-to-markdown-with-pandoc/
https://peintinger.com/?p=365

Still, it required some format correction but it was not disaster.
I hope to finish FullDocument-hdbpp-cm Today.

Greetings to everyone on Tango Meeting in Florence!

**Comment by lzytniak** [comment]
FullDocument-hdbpp-cm docx files:
[FullDocument-hdbpp-cm.docx](https://github.com/tango-controls/tango-doc/files/1055550/FullDocument-hdbpp-cm.docx)
[FullDocument-hdbpp-cm-edited.docx](https://github.com/tango-controls/tango-doc/files/1055549/FullDocument-hdbpp-cm-edited.docx)

**Comment by bourtemb** [comment]
Thanks Łukasz for taking the time to convert the device servers documentation to rst.
These html pages were generated from Pogo.
To ease the maintenance of the documentation, I think we should find an easier way to publish this part of the documentation (Device servers doc) because the work done by Łukasz will have to be done every time there is a new version of the device servers documentation. We should keep it simple...
Could we publish the html files generated by Pogo somewhere and simply add a link to this documentation in tango-doc HDB++ section? 
But we would need to be able to browse the different versions of the device servers docs.
The device servers doc is strongly linked to the source code so I think it would make sense to set-up readthedocs for hdbpp-es and hdbpp-cm repositories and to add a link from http://readthedocs.org/projects/tango-controls HDB++ section to hdbpp-es and hdbpp-cm readthedocs.
What do you think?
I think it would be nice if Pogo could be able to generate doc in rst too. The work done by Łukasz might help as a starting point for this task.

**Comment by LJBD** [comment]
@bourtemb - I think that hosting a separate HDB++ documentation project on ReadTheDocs (or even 2) is a very good idea!

Also, when you generate a Python high level project in POGO, a simple structure of a Sphinx project with sources in `.rst` can be generated as well.
The only problem here is that it doesn't generate the Device Class documentation, it uses a plugin for Sphinx called [devicedoc](https://github.com/vxgmichel/pytango-devicedoc) that was written by @vxgmichel. This plugin imports docstrings from Python modules and AFAIK it cannot be used easily in other languages (I presume that you'd want to use it in C++).
Also AFAIK you can extract documentation from C++ sources with [Breathe](http://breathe.readthedocs.io/en/latest/).

**Comment by piogor** [comment]
I like the idea of having possibility to generate .rst documentation from POGO...
Then, I agree that placing device servers/classes  documentation generated by POGO somewhere else than on tango-doc is a good idea. I am not sure about to many readthedocs projects, however. 
Just keep in mind, that general descriptions, user manuals and internal details of systems like HDB++ should preferable go to the tango-doc. Then tango-doc and POGO generated documentation should link each other.

**Comment by piogor** [comment]
It is already done in tools and extensions section
