### ISSUE TITLE
Remove plurals from glossary

### ISSUE THREAD

**Issue by andygotz** [tango-controls/tango-doc#9]
I propose to remove the plurals from the glossary. It is confusing and is not standard practice. Examples of glossaries without plurals are the git glossary:

https://git-scm.com/docs/gitglossary

How much work is this? I presume it needs to be done by going through all the documentation and removing all markups of concepts in the plural form e.g. :term:`devices` has to replaced by 'devices' only. Correct me if I am wrong.

A typical task we could do during the write-the-doc camp.

**Comment by piogor** [comment]
Yes you are right. When we remove the plurals from the glossary sphinx-build will produce warnings for not exiting terms . So, it is easy to spot them. I estimate that it will up to 2hrs.

**Comment by LJBD** [comment]
Side note: there is an issue with plurals in Sphinx glossaries. To bypass this, use the following command:
```reST
:term:`foos<foo>`
```
Full issue here: http://stackoverflow.com/questions/19403972/writing-terms-in-plural-without-the-redundancy

**Comment by piogor** [comment]
Done.

**Comment by andygotz** [comment]
Excellent - looks much better now! Thanks!
