### ISSUE TITLE
How to write your first Device Class

### ISSUE THREAD

**Issue by piogor** [tango-controls/tango-doc#95]
The how-to is referenced from the 'First steps' but it has no content yet: http://tango-controls.readthedocs.io/en/latest/tutorials-and-howtos/how-tos/how-to-first-device-class.html#how-to-write-first-device-class

This how to should be step-by-step guide of writing a device server with usage of Pogo and make tool.
I suppose it should be more tutorial than how-to.

**Comment by Ingvord** [comment]
> This how to should be step-by-step guide of writing a device server with usage of Pogo and make tool.
I suppose it should be more tutorial than how-to.

As in #112 this must be done in getting started/development section for each language separately. In tutorials I would expect some very exhaustive example of a server (with multi threading, pipes, pushed events etc)

**Comment by piogor** [comment]
Thanks to @mugerin, it is solved with #225.
